# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Post Status

# Model Form Field configuration
form: $/damianlewis/blog/models/status/fields.yaml

# Model Class name
modelClass: DamianLewis\Blog\Models\Status

# Default redirect location
defaultRedirect: damianlewis/blog/posts

# Create page
create:
    title: Create Post Status
    redirect: damianlewis/blog/statuses/update/:id
    redirectClose: damianlewis/blog/statuses
    flashSave: The post status has been created successfully.

# Update page
update:
    title: Edit Post Status
    redirect: damianlewis/blog/statuses
    redirectClose: damianlewis/blog/statuses
    flashSave: The post status has been updated successfully.
    flashDelete: The post status has been deleted successfully.

# Preview page
preview:
    title: Preview Post Status
