# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Post Category

# Model Form Field configuration
form: $/damianlewis/blog/models/category/fields.yaml

# Model Class name
modelClass: DamianLewis\Blog\Models\Category

# Default redirect location
defaultRedirect: damianlewis/blog/posts

# Create page
create:
    title: Create Post Category
    redirect: damianlewis/blog/categories/update/:id
    redirectClose: damianlewis/blog/categories
    flashSave: The post category has been created successfully.

# Update page
update:
    title: Edit Post Category
    redirect: damianlewis/blog/categories
    redirectClose: damianlewis/blog/categories
    flashSave: The post category has been updated successfully.
    flashDelete: The post category has been deleted successfully.

# Preview page
preview:
    title: Preview Post Category
